# Generated by Django 5.2.5 on 2025-08-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BikeRental",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(db_column="일시")),
                (
                    "location_name",
                    models.CharField(db_column="대여소명", max_length=255),
                ),
                ("rental_count", models.FloatField(db_column="대여건수")),
                ("return_count", models.FloatField(db_column="반납건수")),
                ("net_change", models.FloatField(db_column="순변화량")),
                ("avg_temp", models.FloatField(db_column="평균기온(°C)")),
                ("daily_rainfall", models.FloatField(db_column="일강수량(mm)")),
            ],
        ),
    ]
