# Generated by Django 5.2.5 on 2025-08-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikerental",
            name="avg_temp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="daily_rainfall",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="location_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="net_change",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="rental_count",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="return_count",
            field=models.FloatField(),
        ),
    ]
