# Generated by Django 5.2.5 on 2025-08-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0002_alter_bikerental_avg_temp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikerental",
            name="avg_temp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="daily_rainfall",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="location_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="net_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="rental_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bikerental",
            name="return_count",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
